### ISSUE TITLE
Dance app doesn't load

### ISSUE THREAD

**Issue by daleglass** [overte-org/community-apps#19]
Metadata says it's using https://more.overte.org/applications/BodyPaint4/BodyPaint4.js -- which is both the wrong script, and doesn't exist.

**Comment by JulianGro** [comment]
> Updated the metadata.js. I am not sure what to do now to resolve the issue?

Reopening the PR would be fine. Or rather making a new PR from the same branch.

**Comment by AleziaKurdis** [comment]
I fixed it with this PR:
https://github.com/overte-org/community-apps/pull/20
