### ISSUE TITLE
Flashlight in survival kit doesn't work in V8

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/community-apps#22]
It fails with this error:
`[05/30 19:58:29] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 91 column 21 with message: \"Uncaught ReferenceError: eventObj is not defined\" backtrace: ReferenceError: eventObj is not defined\n    at onMoreAppWebEventReceived (https://more.overte.org/applications/survivalKit/app-survivalKit.js:91:22)" `

**Comment by AleziaKurdis** [comment]
Solved instead by pr #24 which fix also 3 other app.
The change should work also on non V8.
