### ISSUE TITLE
Visual rotation glitch with nametags

### ISSUE THREAD

**Issue by GooseVali** [overte-org/community-apps#49]
Sometimes nametags show up with a glitched appearance, where the text and the dark background rectangle get a different rotation. This seems to happen randomly in desktop and in VR. Just standing around in a session with people seems to be enough for it to happen eventually. The rotation offset varies, sometimes large enough to look completely off, sometimes it's smaller and only causes half of the text to appear darker than the other half.

See the screenshot for examples of this glitch.

![20231104225309_1](https://github.com/overte-org/community-apps/assets/150557689/557289aa-ab6c-4f19-9850-bd3e01a9a39f)

**Comment by JulianGro** [comment]
#67 says that it fixes this. Please reopen if this is still an issue.
